//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfUP
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnfreezeRequests
    {
        public int UnfreezeRequestID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> BookID { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Users Users { get; set; }
    }
}
